### ISSUE TITLE
useTorch hook is broken

### ISSUE THREAD

**Issue by karatekid430** [preflower/react-barcode-scanner#313]
The code in use-torch.tsx has issues like that it does not respect the "open" parameter, and leads to poor state management. Cloning the repo and trying to build it from source results in dozens of errors. And there are invalid characters in the package.json "name".

Because the library will not build, I will not be doing a pull request. I will just leave some (very slightly improved) code here and hope that it can be of use to someone. It is sufficiently repaired that it can just be pasted in one's own project to override the useTorch hook from the library, without causing compilation errors.

If the build problems can be sorted or more detailed instructions, then I can possibly refactor the repo to be more consistent. For instance, the fact that trackConstraints can be set in the TSX component opens us up to the possibility of inconsistencies, rather than having one point of truth (hooks). Setting the torch to be enabled in "advanced" here would further make the state inconsistent. Ideally, we would change the toggle to a function that allows the state to be set directly, but for now, I have not made breaking changes.

```tsx
export function useTorch(on = false): [boolean, boolean, () => Promise<void>] {
  const [isTorchOn, setIsTorchOn] = useState(on);
  const [isTorchSupported, setIsTorchSupported] = useState(false);
  const [stream] = useStreamState();
  const track = useMemo(() => {
    return stream?.getVideoTracks()[0];
  }, [stream]);

  useEffect(() => {
    if (track == null) return;
    const capabilities = track.getCapabilities();

    // @ts-expect-error capabilities.torch does not actually exist, but we will use it anyway
    if (capabilities.torch !== undefined) {
      setIsTorchSupported(true);
    }
  }, [track]);

  useEffect(() => {
    track?.applyConstraints({
      advanced: [
        {
          // @ts-expect-error capabilities.torch does not actually exist, but we will use it anyway
          torch: isTorchOn,
        },
      ],
    });
  }, [stream, isTorchOn]);

  const switchTorch = async (state?: boolean): Promise<void> => {
    if (!isTorchSupported) {
      throw new Error(`[react-barcode-scanner]: 
          device does not support torch capability
        `);
    }

    setIsTorchOn((x) => state ?? !x);
  };

  return [isTorchSupported, isTorchOn, switchTorch];
}

**Comment by preflower** [comment]
1. because the root project is a monorepo, its private code, so my name naming is not very standard, I will change it to canonical naming;
2. You mentioned  'The library will not build'; please provide the error details for the package build failure.
3. I suspect you’re using the useTorch hook in multiple places. This was a design oversight, and I will synchronize the open state of useTorch across multiple hooks.
4. I will consider modifying the torch state using a data-driven view when rewriting it.

**Comment by karatekid430** [comment]
Ah thanks. Sorry if I came across as overly-critical. This library was the only one that works well at all. Plus it having its own view to show the video makes things a lot easier than manually attaching the libraries to a stream and a video view object. Although it still is not great on a laptop webcam, it works well on iPhone. The delay needs to be set to 0 for it to work well. I think the zxing library is not very good - it can often not recognise codes when they are clearly readable by myself on the screen. The direct zxing library for ts I did get to work, but it was way too hard to get it to recognise anything. Whilst I know the theory to do image processing, it is too much work for me do replace. If you know how the zxing library can be tuned to work from lower quality video and lower light, I might experiment with those and perhaps see if I can add parameters to this library to adjust these parameters.

There is only one component in which I use the camera and hook. That is repurposed but never run concurrently. The issue is that I want to save the user's torch state and camera device selection in localStorage for that browser. But the torch hook caused issues in me rehydrating that state consistently. I could not use the toggleTorch function in a useEffect, as the toggle would not work before the track/stream has loaded. With my new code, that should now work, as the useEffect in the useTorch will run when the track is loaded.

Some build issues:
- yarn not working due to "name" issue in package.json
- pnpm needs to be in dev dependencies otherwise build results in pnpm not found
- react and @types/react not imported so these imports are broken
- typescript issues such as

Argument of type 'RefObject<HTMLVideoElement | null>' is not assignable to parameter of type 'RefObject<HTMLVideoElement>'.
  Type 'HTMLVideoElement | null' is not assignable to type 'HTMLVideoElement'.
    Type 'null' is not assignable to type 'HTMLVideoElement'.ts(2345)

^ In barcode-scanner.tsx line 18, 19`

Imports are not brought in by package.json:

Cannot find module '@preflower/barcode-detector-polyfill' or its corresponding type declarations.

One thing that really frustrates me about these web camera views is the inability to manually focus by tapping an area of the screen. If the browsers expose these APIs then I would be interested in implementing them in this library if I can get it to build. The frequency in which I can't scan because the camera is focussed too far in the distance is significant.

Is this a fork or is this an original project? I can find similarly-named projects under other repositories but with different versions. If this is a fork then I will need to consider working on the parent, if the parent has had significantly more development.

**Comment by preflower** [comment]
I have already fixed this issue on the `fix/torch` branch. However, as I do not have an Android device, I cannot verify whether the functionality works as expected. Your assistance in testing and validating this feature would be greatly appreciated.
And this project force use `pnpm` to manage project, please install `pnpm` in global.

**Comment by karatekid430** [comment]
I have made this hook which works perfectly for my tested use cases, and it handles Android and iOS correctly. Note my comments about those platforms.

```tsx
import React from "react";
import { DetectedBarcode } from "react-barcode-scanner";
import("react-barcode-scanner/polyfill");

interface UseBarcodeScannerProps {
  constraints?: MediaStreamConstraints;
  formats: string[];
  initialDeviceIndex?: number;
  initialTorchOn?: boolean;
  onDetected: (_: DetectedBarcode[]) => void;
  scanFrequencyMilliseconds: number;
}

const closeStream = async (vref: HTMLVideoElement | null) => {
  if (vref) {
    if (vref.srcObject instanceof MediaStream) {
      vref.srcObject.getTracks().forEach((t) => {
        t.stop();
      });
    }
    vref.srcObject = null;
  }
};

export function useBarcodeScanner(props: UseBarcodeScannerProps) {
  const video = React.useRef<HTMLVideoElement>(null);
  const [devices, setDevices] = React.useState<MediaDeviceInfo[]>([]);
  const [selectedDeviceIndex, setDeviceIndex] = React.useState<number>(0);
  const device = React.useMemo(() => devices[selectedDeviceIndex], [devices, selectedDeviceIndex]);
  const [torchSupported, setTorchSupported] = React.useState<boolean>(false);
  const [torchEnabled, setTorch] = React.useState<boolean>(props.initialTorchOn ?? false);

  React.useEffect(() => {
    const stream = video.current?.srcObject;
    if (stream instanceof MediaStream) {
      stream.getVideoTracks()?.[0]?.applyConstraints({
        advanced: [
          {
            torch: torchEnabled,
          } as MediaTrackConstraints,
        ],
      });
    }
  }, [torchEnabled]);

  const getStream = React.useCallback(
    async (dev: MediaDeviceInfo) => {
      const stream = await navigator.mediaDevices.getUserMedia({
        ...props.constraints,
        video: {
          advanced: [
            {
              torch: torchEnabled,
            } as MediaTrackConstraints,
          ],
          deviceId: dev.deviceId,
        },
      });

      const v = video.current;
      const track = stream.getVideoTracks()?.[0];
      setTorchSupported((track?.getCapabilities?.() as { torch?: string })?.torch !== undefined);

      if (v) v.srcObject = stream;
    },
    [torchEnabled],
  );

  React.useEffect(() => {
    let intervalId: NodeJS.Timeout | null = null;

    intervalId = setInterval(async () => {
      if (video.current) {
        const imageBitmap = await createImageBitmap(video.current);

        const detector = new BarcodeDetector({
          formats: props.formats,
        });

        try {
          props.onDetected(await detector.detect(imageBitmap));
        } catch (error) {
          console.error("Barcode detection failed:", error);
        }
      }
    }, props.scanFrequencyMilliseconds);

    return () => {
      if (intervalId) {
        clearInterval(intervalId);
      }
    };
  }, [props.formats, props.scanFrequencyMilliseconds]);

  React.useEffect(() => {
    const vref = video.current;
    closeStream(vref);
    device && getStream(device);
    return () => {
      closeStream(vref);
    };
  }, [device]);

  const getCameras = React.useCallback(async () => {
    const tempStream = await navigator.mediaDevices.getUserMedia({
      video: {
        facingMode: {},
      },
    });
    tempStream.getTracks().forEach((t) => t.stop());
    const enumeratedDevices = await navigator.mediaDevices.enumerateDevices();
    const videoDevices = enumeratedDevices.filter(
      (device) => device.kind === "videoinput" && !!device.deviceId,
    );

    setDeviceIndex(props.initialDeviceIndex ?? 0);
    setDevices(videoDevices);
  }, []);

  React.useEffect(() => {
    getCameras();
  }, []);

  return {
    device,
    devices,
    setDeviceIndex,
    setTorch,
    torchEnabled,
    torchSupported,
    video,
  };
}
```

**Comment by karatekid430** [comment]
Here's an example from Next.js App Router with Typescript and React 19:

```tsx
"use client";

import styles from "./BarcodeScanner.module.css";
import { useBarcodeScanner } from "./useBarcodeScanner";

interface Props {
  onClose: () => void;
  onScanBarcode: (code: string) => void;
}

export function BarcodeScanner(props: Props) {
  const scanner = useBarcodeScanner({
    formats: ["ean_13"],
    initialDeviceIndex: Number.parseInt(localStorage.getItem("cameraIndex") ?? "0", 10),
    initialTorchOn: localStorage.getItem("torch") === "1",
    onDetected: (barcodes) => {
      if (barcodes?.[0]) {
        props.onScanBarcode(barcodes[0].rawValue);
      }
    },
    scanFrequencyMilliseconds: 100,
  });

  return (
    <div className={styles.container}>
      <video ref={scanner.video} className={styles.video} autoPlay muted playsInline />
      <div className={styles.scannerOverlay}>
        <div className={styles.scanLine} />
      </div>
      <div className={styles.buttonContainer}>
        {scanner.torchSupported && (
          <button
            onClick={() => {
              scanner.setTorch(!scanner.torchEnabled);
              localStorage.setItem("torch", !scanner.torchEnabled ? "1" : "0");
            }}
            className={styles.closeButton}
          >
            {scanner.torchEnabled ? (
              <svg
                width="32"
                height="32"
                viewBox="0 -0.5 25 25"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M5.0553 15.7213C4.1797 15.7044 3.48357 14.9809 3.5003 14.1053V10.8733C3.48357 9.99772 4.1797 9.27428 5.0553 9.25732H10.7153C11.074 9.25645 11.4209 9.12855 11.6943 8.89632L13.5253 7.35332C13.9965 6.96545 14.6514 6.89018 15.1983 7.16103C15.7452 7.43189 16.0823 7.99846 16.0593 8.60832V16.3703C16.0823 16.9802 15.7452 17.5467 15.1983 17.8176C14.6514 18.0885 13.9965 18.0132 13.5253 17.6253L11.6943 16.0823C11.4209 15.8501 11.074 15.7222 10.7153 15.7213H5.0553Z" />
                <path d="M11.3683 12.4894C11.3683 12.0751 11.0325 11.7394 10.6183 11.7394C10.2041 11.7394 9.86829 12.0751 9.86829 12.4894H11.3683ZM9.86829 15.7214C9.86829 16.1356 10.2041 16.4714 10.6183 16.4714C11.0325 16.4714 11.3683 16.1356 11.3683 15.7214H9.86829ZM21.1461 8.25738C21.4863 8.02111 21.5706 7.55378 21.3343 7.21356C21.098 6.87333 20.6307 6.78907 20.2905 7.02533L21.1461 8.25738ZM17.9635 8.64133C17.6233 8.8776 17.539 9.34494 17.7753 9.68516C18.0115 10.0254 18.4789 10.1096 18.8191 9.87338L17.9635 8.64133ZM21.5003 13.2394C21.9145 13.2394 22.2503 12.9036 22.2503 12.4894C22.2503 12.0751 21.9145 11.7394 21.5003 11.7394V13.2394ZM19.1683 11.7394C18.7541 11.7394 18.4183 12.0751 18.4183 12.4894C18.4183 12.9036 18.7541 13.2394 19.1683 13.2394V11.7394ZM20.2961 17.9538C20.6366 18.1897 21.1038 18.105 21.3397 17.7645C21.5757 17.4241 21.4909 16.9568 21.1505 16.7209L20.2961 17.9538ZM18.8185 15.1049C18.478 14.869 18.0108 14.9537 17.7748 15.2942C17.5389 15.6346 17.6236 16.1019 17.9641 16.3378L18.8185 15.1049ZM9.86829 12.4894V15.7214H11.3683V12.4894H9.86829ZM20.2905 7.02533L17.9635 8.64133L18.8191 9.87338L21.1461 8.25738L20.2905 7.02533ZM21.5003 11.7394H19.1683V13.2394H21.5003V11.7394ZM21.1505 16.7209L18.8185 15.1049L17.9641 16.3378L20.2961 17.9538L21.1505 16.7209Z" />
              </svg>
            ) : (
              <svg
                width="32"
                height="32"
                viewBox="0 -0.5 25 25"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M8.0553 15.7213C7.1797 15.7044 6.48357 14.9809 6.5003 14.1053V10.8733C6.48357 9.99772 7.1797 9.27428 8.0553 9.25732H13.7153C14.074 9.25645 14.4209 9.12855 14.6943 8.89632L16.5253 7.35332C16.9965 6.96545 17.6514 6.89018 18.1983 7.16103C18.7452 7.43189 19.0823 7.99846 19.0593 8.60832V16.3703C19.0823 16.9802 18.7452 17.5467 18.1983 17.8176C17.6514 18.0885 16.9965 18.0132 16.5253 17.6253L14.6943 16.0823C14.4209 15.8501 14.074 15.7222 13.7153 15.7213H8.0553Z" />
                <path d="M13.6183 12.4894V15.7214" />
              </svg>
            )}
          </button>
        )}
        <button
          className={styles.cycleButton}
          onClick={() => {
            scanner.setDeviceIndex((prevIndex) => {
              const newIndex = (prevIndex + 1) % scanner.devices.length;
              localStorage.setItem("cameraIndex", newIndex.toString());
              return newIndex;
            });
          }}
        >
          {scanner.device?.label || "No Device"}
        </button>
        <button onClick={props.onClose} className={`${styles.closeButton}`}>
          <svg
            width="32"
            height="32"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  );
}
```

**Comment by karatekid430** [comment]
I forgot the BarcodeScanner.module.css:

```css
.container {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: black;
}

.video {
    position: absolute;
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.buttonContainer {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px 8px;
    gap: 8px;
}

.closeButton {
    background: rgba(0, 0, 0, 0.5);
    border: none;
    color: white;
    width: 50px;
    height: 50px;
    border-radius: 8px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 50px;
    height: 50px;
    flex-shrink: 0;
}

.cycleButton {
    flex-grow: 1;
    background: rgba(0, 0, 0, 0.5);
    border: none;
    color: white;
    padding: 0px 16px;
    border-radius: 8px;
    cursor: pointer;
    font-size: 16px;
    transition: background 0.3s;
    display: inline-block;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    height: 50px;
}

.scannerOverlay {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 80%;
    max-width: 500px;
    aspect-ratio: 4/3;
    border: 2px solid rgba(255, 255, 255, 0.5);
    border-radius: 16px;
}

.scanLine {
    position: absolute;
    width: 100%;
    height: 2px;
    background: #ff0000;
    top: 50%;
    transform: translateY(-50%);
    animation: scan 2s linear infinite;
}

@keyframes scan {
    0% {
        box-shadow: 0 0 4px #ff0000;
    }

    50% {
        box-shadow: 0 0 12px #ff0000;
    }

    100% {
        box-shadow: 0 0 4px #ff0000;
    }
}
```
